/**
 * GENERATED by server/scripts/template-bg/render.mjs — do not edit by hand.
 * Template cards that have a painted backdrop in public/template-bg/, keyed
 * by card key, with a content hash so a repainted image is never served stale.
 */
export const TEMPLATE_BACKDROPS: Record<string, string> = {
  'anime-edit': '3323b1b0',
  'archives': '6d37e781',
  'aura': '76efe5d1',
  'beat-karaoke': '37ed197f',
  'blockbuster': 'a3beb5bc',
  'bubble-candy': 'febe46a7',
  'cinematic-subtitle': 'b8fc98b7',
  'creator-yellow-box': '1b56148b',
  'full-sentence': 'dbd266f6',
  'hero-punch': '5fb4945b',
  'hero-word': 'c3b9e56f',
  'industrial': '9a54baa9',
  'livingBlue': '00436fe7',
  'livingOrange': '4434b5bf',
  'livingPurple': '237fac16',
  'livingRed': '0c3cfeeb',
  'livingTeal': '78700600',
  'marker-pen': 'e86e3e8c',
  'poppins-bold': '0c63c990',
  'roboto-word': '106feb18',
  'scribble': '6056fbcd',
  'soft-flicker': 'a9319652',
  'stack-verse': '24956074',
  'swiss': 'fea7dd34',
  'the-big-red': '9fb1988b',
  'tiktok-classic': '667c56eb',
  'tiktok-pill': 'b7512105',
  'typewriter': '136eb4d4',
  'word-blast': 'f207a3e3',
  'word-reveal': 'a749ba8a',
};
